imagenet_templates_small = [
    "a recording of a {}",
    "a {} recording",
    "a synthesized {} audio",
    "a cropped recording of the {}",
    "the recording of a {}",
    # "a clean {} audio"
    "a clean {} recording",
    "a distorted {} audio",
    "a dark {} audio recording",
    "my {} recording",
    "a cool {} audio",
    "a close-up recording of a {}",
    "a bright {} audio recording",
    # "a cropped recording of a {}",
    "the {} recording",
    "a high-quality {} recording",
    "a recording of one {}",
    "a close-up recording of the {}",
    "a rendition of the {}",
    "a clean {} audio recording",
    "a synthesized {} rendition",
    "a high-quality {} audio",
    "a good {} audio recording",
    "a nice {} audio recording",
    "the small {} audio",
    "a loud recording of a {}",
    # "the large {} audio"
    # "a cool {} audio recording",
    # "a small {} audio recording",
    "the sound of a {}",
    "the sound of {}",
    "high quality {} audio",
]


imagenet_templates_small_class = [
    "a recording of a {} {}",
    "a {} {} recording",
    "a synthesized {} {} audio",
    "a cropped recording of the {} {}",
    "the recording of a {} {}",
    # "a clean {} {} audio"
    "a clean {} {} recording",
    "a distorted {} {} audio",
    "a dark {} {} audio recording",
    "my {} {} recording",
    "a cool {} {} audio",
    "a close-up recording of a {} {}",
    "a bright {} {} audio recording",
    # "a cropped recording of a {} {}",
    "the {} {} recording",
    "a high-quality {} {} recording",
    "a recording of one {} {}",
    "a close-up recording of the {} {}",
    "a rendition of the {} {}",
    "a clean {} {} audio recording",
    "a synthesized {} {} rendition",
    "a high-quality {} {} audio",
    "a good {} {} audio recording",
    "a nice {} {} audio recording",
    "the small {} {} audio",
    "a loud recording of a {} {}",
    # "the large {} {} audio"
    # "a cool {} {} audio recording",
    # "a small {} {} audio recording",
    "the sound of a {} {}",
    "the sound of {} {}",
    "high quality {} {} audio",
]

imagenet_style_templates_small = [
    "an audio recording in the style of {}",
    "a recording in the style of {}",
    "music in the style of {}",
    "a song in the style of {}",
    "an audio rendering in the style of {}",
    "a cropped audio recording in the style of {}",
    "the audio recording in the style of {}",
    "a clean audio recording in the style of {}",
    "a distorted audio recording in the style of {}",
    "a high quality audio recording in the style of {}",
    "an audio composition in the style of {}",
    "a good audio recording in the style of {}",
    "a close-up audio recording in the style of {}",
    "an audio rendition in the style of {}",
    "a nice audio recording in the style of {}",
]

text_editability_templates=[
    "a jazz song with a {}",
    "a rock song with a {}",
    "a disco song with a {}",
    "a techno song with a {}",
    "a heavy metal song with a {}",
    "a recording of a {} in a small room",
    "a recording of a {} in a cathedral",
    "a recording of a {} under water",
    "a gramophone recording of a {}",
    "a recording of a {} song with a rock drum beat accompaniment",
    "a recording of a {} song with a jazz drum beat accompaniment",
    "a recording of a {} song with a hip hop drum beat accompaniment",
    "a recording of a {} song with a man singing",
    "a recording of a {} in the rain",
    "a recording of a {} with footsteps",
    "a recording of a {} in a big crowd",
    "a recording of a vibrant {} solo with a classical guitar accompaniment",
    "a recording of a {} with a synth baseline accompaniment",
    "a recording of a {} with a saxophone accompaniment",
    "a recording of a {} playing a happy tune",
    "a recording of a {} playing a sad tune",
]

text_editability_templates_small=[
    "a recording of a {} in a jazz style",
    "a recording of a {} in a rock style",
    "a recording of a {} in a big room",
    "a recording of a {} in a small room",
    "a recording of a {} in a cathedral",
    "a recording of a {} under water",
    "a recording of a {} song with a rock drum beat",
    "a recording of a {} song with a jazz drum beat",
    "a recording of a {} song with a hip hop drum beat",
    "a recording of a {} song with heavy metal distorted guitar",
    "a recording of a {} song with a man singing",
    "a distorted recording of a {}",
    "a clean recording of a {}",
    "an old low quality recording of {}",
    "a high quality studio recording of {}",
    "a recording of {} with a lot of reverb",
    "a recording of {} with a lot of echo",
    "a recording of {} with a lot of bass",
    "a recording of {} without any bass",
    "a recording of {} with a lot of high frequencies",
    "a recording of {} without any high frequencies",
    "a recording of a muted {}",
    "a recording of {} with a lot of distortion",
    "the sound of {} with a man speaking",
    "a recording of {} with a man speaking",
    "a synthesized recording of {}",
    "a recording of a midi electronic version of {}",
    "a recording of a midi electronic version of {} with a drum machine beat",
    "high quality {} audio with a drum machine beat",
    "a recording of a metal {}",
    "a recording of a wooden {}",
    "a recording of a plastic {}",
    "a recording of a glass {}",
    "a recording of a ceramic {}",
    "a recording of a rubber {}",
    "a recording of a cardboard {}",
    "a recording of a paper {}",
    "the sound of an electronic midi {}",
    "the sound of a {} in a disco style",
    "the sound of a {} in a rock style",
    "the sound of a {} in a jazz style",
    "the sound of a {} in a hip hop style",
    "the sound of a {} in a classical style",
    "the sound of a {} in a country style",
    "the sound of a {} in a pop style",
    "the sound of a {} in a metal style",
    "the sound of a {} in a punk style",
    "the sound of a {} in a reggae style",
    "the sound of a {} in a techno style",
    "the sound of a {} in a dubstep style",
    "the sound of a {} with a rock drum beat",
    "the sound of a {} with a drum breakbeat",
    "the sound of a {} with a hip hop drum beat",
]

reconstruction_templates=[
    "A recording of a {}",
    "The sound of {}",
    "A {} recording",
    "A high-quality {} recording",
    "A clean {} recording",
    "The sound of a {}",
    "A recording of {}",
    "A {}",
    "{}",
]

reconstruction_templates_instrument=[
    "A recording of a {} playing music",
    "A recording of a {} playing",
    "A recording of a {}",
    "The sound of {}",
    "The sound of {} playing",
    "A {} music recording",
    "The sound of a {}",
    "The sound of a {} playing",
    "The sound of a {} playing music",
    "A {} music",
    "{} music",
]

reconstruction_templates_music=[
    "a recording of a {} music",
    "the sound of {} music",
    "a {} music recording",
    "a high-quality {} music recording",
    "a clean {} music recording",
    "the sound of a {} music",
    "a recording of {} music",
    "a {} music",
    "{} music",
]

minimal_templates=[
    "{}",
]

instrument_keywords = [
    "guitar",
    "piano",
    "violin",
    # "cello",
    # "bass",
    "drums",
    # "trumpet",
    "saxophone",
    # "jaw harp",
    # "flute",
    # "synthesizer",
    # "oud",
    # "banjo",
    # "bouzouki",
    "clarinet",
    # "duduk",
    # "darbuka",
    # "ney",
    # "santur",
    # "fiddle"
    # "kick drum",
    "snare drum",
    "hi-hat",
    # "ride cymbal",
    # "crash cymbal",
    # "tom-tom",
    # "bass drum",
    # "floor tom",
    # "tambourine",
    # "cowbell",
    # "conga",
    # "bongo",
    # "timpani",
    # "marimba",
    # "xylophone",
    # "electric guitar",
    # "acoustic guitar",
    # "classical guitar",
    # "bass guitar",
    # "gregorian chant",
    # "choir",
    # "opera singer",
    # "singer",
    
]

instrument_reconstruction_templates = [
    "A recording of a {}",
    "The sound of {}",
    "A {} recording",
    "A high-quality {} recording",
    "A vibrant {} solo",
    "A {} traditional song",
    "A vibrant {} recording"
]

music_genre_keywords = [
    "jazz",
    "rock and roll",
    "punk rock",
    "heavy metal",
    "classical music",
    "country music",
    "pop music",
    "hip hop",
    "techno",
]


music_keywords = [
    "guitar",
    "piano",
    "violin",
    "cello",
    "bass",
    "drums",
    "trumpet",
    "saxophone",
    "jaw harp",
    "flute",
    "synthesizer",
    "jazz",
    "rock and roll",
    "punk rock",
    "heavy metal",
    "classical music",
    "country music",
    "pop music",
    "hip hop",
    "techno",
]

oud_prompts = [
    "A recording of an oud",
    "A recording of an oud playing music",
    "A recording of a turkish oud",
    "A recording of a traditional turkish oud",
    "A recording of an oud playing traditional turkish music",
    "The sound of an oud",
    "The sound of a traditional turkish oud",
    "The sound of a turkish oud traditional string instrument",
    "The sound of oud music"
]